# Travis configuration file based on https://docs.travis-ci.com/user/languages/python/
# Read more under http://docs.travis-ci.com/user/build-configuration/
# THIS SCRIPT IS SUPPOSED TO BE AN EXAMPLE. MODIFY IT ACCORDING TO YOUR NEEDS!

language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"


# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install -U pip
  - pip install tox pytest pytest-cov coverage coveralls
  - pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script:
  - pytest
  
after_success:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then coveralls || echo "failed"; fi


